### ISSUE TITLE
Please make sure the contact us page is linked to DB

### ISSUE THREAD

**Issue by pabin-shrestha** [Anil-KHANAL/Tours-Management-system#1]
link the form to the database or also you can choose or edit the necessary tasks.
also if you can make it better you can try it on yourself.
I have uploaded some templates in the basecamp as well.

**Comment by Anil-KHANAL** [comment]
The issue has been solved.

**Comment by GovindBhusal007** [comment]
I have already completed the Contact Us page, I have used Django and the MySQL for storing the data of Contact Us page.

**Comment by pabin-shrestha** [comment]
Thank you, Govind for fixing the issue.
