### ISSUE TITLE
ModuleFoundNotError : 'django.shorcuts'

### ISSUE THREAD

**Issue by GovindBhusal007** [Anil-KHANAL/Tours-Management-system#2]
Pabin, can you solve this problem or find some resourceful data regarding this problem? I have even attached the screenshot please check it out??
![Screenshot (350)](https://user-images.githubusercontent.com/81344630/114608792-c9017500-9cbd-11eb-9f5f-a1f83d40b0e3.png)

**Comment by GovindBhusal007** [comment]
I have found my mistake regarding this problem. I miss spelled the function.

**Comment by Anil-KHANAL** [comment]
Govind, please consult  this problem with Pabin

**Comment by pabin-shrestha** [comment]
Anil, the issue has already been solved.
Thank you.
