### ISSUE TITLE
The view contact.views.Insertrecord didn't return an HttpResponse object. It returned None instead

### ISSUE THREAD

**Issue by GovindBhusal007** [Anil-KHANAL/Tours-Management-system#3]
Pabin, can you solve this problem or find some resourceful data regarding this problem? I have even attached the screenshot please check it out??
![Screenshot (362)](https://user-images.githubusercontent.com/81344630/114671014-588d3f00-9d23-11eb-9f28-7b9c33a6946b.png)

**Comment by GovindBhusal007** [comment]
There was a mistake in else if statement, it has been fixed now.

**Comment by pabin-shrestha** [comment]
Thank you, Govind for fixing the error.

**Comment by Dambar-j** [comment]
this issue has been fixed
