### ISSUE TITLE
The logo is missing in the page

### ISSUE THREAD

**Issue by pabin-shrestha** [Anil-KHANAL/Tours-Management-system#4]
###  Thank you.

**Comment by GovindBhusal007** [comment]
That part will be done by our frontend developers, prabin.

**Comment by pabin-shrestha** [comment]
ok govind.

**Comment by GovindBhusal007** [comment]
I have send them some logos prabin so i think it will be okay to close this issue now.

**Comment by pabin-shrestha** [comment]
ok, Govind. I hope they have looked for the logo and attached it to the page. 
Thankyou for creating the logo.
