### ISSUE TITLE
Booking Page Run time error. 

### ISSUE THREAD

**Issue by GovindBhusal007** [Anil-KHANAL/Tours-Management-system#5]
Guys plz find the useful data regarding this problem. 
![Screenshot (514)](https://user-images.githubusercontent.com/81344630/117969695-790ee000-b347-11eb-9f3b-6721157d1b28.png)

**Comment by pabin-shrestha** [comment]
Govind, I figured out the issue. It seems your project URL is not properly linked with your home URL. That's causing the problem fix it and I am sure it will sort out the problem.

**Comment by GovindBhusal007** [comment]
Thanks Pabin for your help, i will make the changes and submit the file again.
